version: '2'
services:
  nginx:
    build: ./nginx/dev
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres
    env_file: .env
  web:
    build: .
    command: bundle exec unicorn_rails -c config/unicorn.rb
    env_file: .env
    volumes:
      - .:/opt/minhassenhas
    depends_on:
      - db
