version: '2'
services:
  nginx:
    build: ./nginx/prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres
    env_file: .env.production
  web:
    image: webgoal/minhassenhas
    command: bundle exec unicorn_rails -c config/unicorn.rb
    env_file: .env.production
    depends_on:
      - db
